filter:
    paths: ["src/*"]

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        docker: true
    tests:
        override:
            - 'make unit'
            - 
                command: 'make code-coverage'
                coverage:
                    file: 'bin/clover.xml'
                    format: 'clover'